Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/ViewModels/Conta/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Open.ProjetoPadrao.Web.ViewModels.Admin
{
  public class LoginViewModel
  {
    [Required(ErrorMessage = "Informe o usuário")]
    [Display(Name = "Usuário")]
    public string Login { get; set; }

    [Required(ErrorMessage = "Informe a senha")]
    [DataType(DataType.Password)]
    [Display(Name = "Senha")]
    public string Senha { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/ViewModels/Conta/MinhaContaViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Open.ProjetoPadrao.Web.ViewModels.Admin
{
  public class MinhaContaViewModel
  {
    [Required(ErrorMessage = "Informe a senha atual")]
    [StringLength(32, ErrorMessage = "A senha atual deve ter no mínimo 1 e no máximo 32 caracteres", MinimumLength = 1)]
    [DataType(DataType.Password)]
    [Display(Name = "Senha Atual")]
    public string SenhaAtual { get; set; }

    [Required(ErrorMessage = "Informe a nova senha")]
    [StringLength(32, ErrorMessage = "A nova senha deve ter no mínimo 6 e no máximo 32 caracteres", MinimumLength = 6)]
    [DataType(DataType.Password)]
    [Display(Name = "Nova Senha")]
    public string NovaSenha { get; set; }

    [Required(ErrorMessage = "Confirme a senha")]
    [StringLength(32, ErrorMessage = "A nova senha deve ter no mínimo 6 e no máximo 32 caracteres", MinimumLength = 6)]
    [DataType(DataType.Password)]
    [Compare("NovaSenha", ErrorMessage = "As senhas não coincidem")]
    [Display(Name = "Confirme a Senha")]
    public string ConfirmacaoSenha { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Controllers/ContaController.cs
using System;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.Script.Serialization;
using Open.Framework.Enums;
using Open.Framework.Classes;
using Open.Framework.Seguranca;
using Open.ProjetoPadrao.Web.Entities;
using Open.ProjetoPadrao.Web.Properties;
using Open.ProjetoPadrao.Web.UnitOfWork;
using Open.ProjetoPadrao.Web.Attributes;
using Open.ProjetoPadrao.Web.Authentication;
using Open.ProjetoPadrao.Web.ViewModels.Admin;

namespace Open.ProjetoPadrao.Web.Areas.Admin.Controllers
{
  public class ContaController : BaseController
  {
    public ContaController(IUnitOfWork unitOfWork) : base(unitOfWork) { }

    [HttpGet, NotAjax, AllowAnonymous]
    public ActionResult Entrar()
    {
      return View();
    }

    [HttpPost, AjaxOnly, AllowAnonymous, ValidateAntiForgeryToken]
    public JsonResult Entrar(LoginViewModel model)
    {
      var retorno = new RetornoJson(true, string.Empty, FormsAuthentication.LoginUrl);

      try
      {
        var usuario = _unitOfWork.UsuarioRepository.BuscarUsuario(model.Login);

        if (usuario != null)
        {
          if (usuario.Ativo)
          {
            if (usuario.UsuarioPerfil.AcessoSistemaAdmin)
            {
              if (Criptografia.VerificarValoresCriptografados(model.Senha, usuario.Senha, TipoCriptografia.BCrypt))
              {
                GravarCookie(usuario);

                retorno.Erro = false;
                retorno.UrlRetorno = FormsAuthentication.GetRedirectUrl(usuario.Pessoa.Email, false);
              }
              else
              {
                retorno.Mensagem = Mensagens.UsuarioSenhaInvalidos;
              }
            }
            else
            {
              retorno.Mensagem = Mensagens.AcessoNegadoAdmin;
            }
          }
          else
          {
            retorno.Mensagem = Mensagens.UsuarioInativo;
          }
        }
        else
        {
          retorno.Mensagem = Mensagens.UsuarioSenhaInvalidos;
        }
      }
      catch
      {
        retorno.Mensagem = Mensagens.ErroLogin;
      }

      return Json(retorno);
    }

    [HttpGet]
    public ActionResult MinhaConta()
    {      
      return View(new MinhaContaViewModel());
    }

    [HttpPost, ValidateAntiForgeryToken]
    public JsonResult SalvarMinhaConta(MinhaContaViewModel model)
    {
      var retorno = new RetornoJson(true, "Ocorreu um erro ao alterar sua senha", string.Empty);

      try
      {
        var usuario = _unitOfWork.UsuarioRepository.BuscarUsuario(UsuarioLogado.Login);

        if (usuario != null)
        {
          if (Criptografia.VerificarValoresCriptografados(model.SenhaAtual, usuario.Senha, TipoCriptografia.BCrypt))
          {
            string senhaCriptografada = Criptografia.Criptografar(model.NovaSenha, TipoCriptografia.BCrypt);
            _unitOfWork.UsuarioRepository.AlterarSenhaUsuario(UsuarioLogado.IDUsuario, senhaCriptografada);

            retorno.Erro = false;
            retorno.Mensagem = "Sua senha foi alterada com sucesso!";
          }
          else
          {
            retorno.Mensagem = "Senha atual inválida";
          }
        }
      }
      catch { }

      return Json(retorno);
    }

    [HttpGet, NotAjax]
    public void Sair()
    {
      HttpContext.Response.Cookies.Remove(Properties.Configs.NomeCookie);
      Session["MenusPermitidos"] = null;

      FormsAuthentication.SignOut();
      FormsAuthentication.RedirectToLoginPage();
    }

    private void GravarCookie(Usuario usuarioLogado)
    {
      var model = new UsuarioSerializeModel();

      model.IDUsuario = usuarioLogado.IDUsuario;
      model.IDUsuarioPerfil = usuarioLogado.IDUsuarioPerfil;
      model.IDPessoa = usuarioLogado.IDPessoa;
      model.Nome = usuarioLogado.Pessoa.NomeCompleto;
      model.Email = usuarioLogado.Pessoa.Email;
      model.Login = usuarioLogado.Login;
      model.Ativo = usuarioLogado.Ativo;
      model.SuperUser = usuarioLogado.UsuarioPerfil.SuperUser;
      model.CadastraPagina = usuarioLogado.UsuarioPerfil.CadastraPagina;
      model.EditaPagina = usuarioLogado.UsuarioPerfil.EditaPagina;

      StringBuilder sbActions = new StringBuilder();
      string nomeAction = string.Empty;

      var usuarioPerfilMenus = usuarioLogado.UsuarioPerfil.UsuarioPerfilMenus;

      foreach (UsuarioPerfilMenu usuarioPerfilMenu in usuarioPerfilMenus)
      {
        if (usuarioPerfilMenu.Menu != null && !string.IsNullOrEmpty(usuarioPerfilMenu.Menu.Action) && !string.IsNullOrEmpty(usuarioPerfilMenu.Menu.Controller))
        {
          nomeAction = usuarioPerfilMenu.Menu.Action.Equals("Index") ? usuarioPerfilMenu.Menu.Controller : usuarioPerfilMenu.Menu.Action;
          sbActions.Append(nomeAction + ";");
        }

        if (usuarioPerfilMenu.Menu != null)
        {
          foreach (Menu menuFilho in usuarioPerfilMenu.Menu.MenusFilhos)
          {
            if (!string.IsNullOrEmpty(menuFilho.Action) && !string.IsNullOrEmpty(menuFilho.Controller))
            {
              nomeAction = menuFilho.Action.Equals("Index") ? menuFilho.Controller : menuFilho.Action;
              sbActions.Append(nomeAction + ";");
            }
          }
        }
      }

      model.ActionsPermitidas = sbActions.ToString().ToLower();

      string userData = new JavaScriptSerializer().Serialize(model);

      var authTicket = new FormsAuthenticationTicket(
               1,
               usuarioLogado.Pessoa.NomeCompleto,
               DateTime.Now,
               DateTime.Now.AddHours(8),
               false,
               userData,
               FormsAuthentication.FormsCookiePath);

      string encTicket = FormsAuthentication.Encrypt(authTicket);
      HttpCookie faCookie = new HttpCookie(Configs.NomeCookie, encTicket);
      HttpContext.Response.Cookies.Add(faCookie);
    }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Conta/Entrar.cshtml
@model Open.ProjetoPadrao.Web.ViewModels.Admin.LoginViewModel
@{
  Layout = null;
}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>A.Yoshii Imobiliários Administrador | Entrar</title>
  @Styles.Render("~/bundles/admin/css/login")
</head>

<body class="gray-bg">

  <div class="limiter">
    <div class="container-login100">
      <div class="wrap-login100">

        @using (Ajax.BeginForm("Entrar", "Login",
        new AjaxOptions()
        {
            HttpMethod = "POST",
            OnBegin    = "inicioLogin",
            OnSuccess  = "sucessoLogin",
            OnFailure  = "falhaLogin",
        },
        new { id = "formLoginAdmin", @class = "login100-form validate-form" }))
        {
          @Html.AntiForgeryToken()

          <span class="login100-form-title p-b-43">
            <img src="@Url.Content("~/Areas/Admin/Assets/imgs/logo-login.jpg")" alt="Logo A.Yoshii" />
          </span>

          <div class="wrap-input100 validate-input" data-validate="Informe seu login">
            @Html.TextBoxFor(m => m.Login, new { @class = "input100", data_id = "txtCampoLogin", id = "txtLogin", placeholder = "Login" })
            <span class="focus-input100"></span>
            <span class="label-input100"></span>
          </div>

          <div class="wrap-input100 validate-input" data-validate="Informe sua senha">
            @Html.PasswordFor(m => m.Senha, new { @class = "input100", data_id = "txtCampoLogin", id = "txtSenha", @type = "password", placeholder = "Senha" })
            <span class="focus-input100"></span>
            <span class="label-input100"></span>
          </div>
          <div class="flex-sb-m w-full p-t-3 p-b-32">
            <div>
              <a href="#" class="txt1">
                Esqueceu a senha?
              </a>
            </div>
          </div>
          <div class="container-login100-form-btn">
            <button id="btnLoginAdmin" type="submit" class="login100-form-btn" data-loading-text="<i class='fa fa-circle-notch fa-spin'></i>">Entrar</button>
            <div id="divMensagemErroLogin" class="alert alert-danger" hidden="hidden"></div>
          </div>
        }
        <div class="login100-more" style="background-image: url('@Url.Content("~/Areas/Admin/Assets/imgs/background-login.jpg")');"></div>
      </div>
    </div>
  </div>
  @Scripts.Render("~/bundles/admin/js/login")
</body>
</html>

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Conta/MinhaConta.cshtml
@model Open.ProjetoPadrao.Web.ViewModels.Admin.MinhaContaViewModel
@{
  ViewBag.Title = "Minha Conta";
  Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-9">
    <h2>Minha Conta</h2>
    <ol class="breadcrumb">
      <li>
        <a href="@Url.Action("Index", "Principal")">Dashboard</a>
      </li>
      <li class="active">
        <strong>Minha Conta</strong>
      </li>
    </ol>
  </div>
</div>

@using (Ajax.BeginForm("SalvarMinhaConta", "Conta",
       new AjaxOptions()
       {
         HttpMethod = "POST",
         OnBegin = "inicioCadastro",
         OnSuccess = "sucessoCadastro",
         OnFailure = "falhaCadastro",
       },
       new { id = "formCadastroMinhaConta", @class = "m-t", role = "form" }))
{
  @Html.AntiForgeryToken()

  <div class="wrapper wrapper-content">
    <div class="ibox float-e-margins">
      <div class="ibox-content padding-bottom">
        <div class="row">
          <div class="form-group">
            <div class="col-lg-3">
              @Html.LabelFor(a => a.SenhaAtual)
              @Html.TextBoxFor(a => a.SenhaAtual, new { placeholder = "Senha Atual", @class = "form-control m-b", @maxlength = "32", @type = "password" })
              @Html.ValidationMessageFor(a => a.SenhaAtual)
            </div>
            <div class="col-lg-3">
              @Html.LabelFor(a => a.NovaSenha)
              @Html.TextBoxFor(a => a.NovaSenha, new { placeholder = "Nova Senha", @class = "form-control m-b", @maxlength = "32", @type = "password" })
              @Html.ValidationMessageFor(a => a.NovaSenha)
            </div>
            <div class="col-lg-3">
              @Html.LabelFor(a => a.ConfirmacaoSenha)
              @Html.TextBoxFor(a => a.ConfirmacaoSenha, new { placeholder = "Confirmação de Senha", @class = "form-control m-b", @maxlength = "32", @type = "password" })
              @Html.ValidationMessageFor(a => a.ConfirmacaoSenha)
            </div>
          </div>
        </div>
        <div class="hr-line-dashed"></div>

        <!-- BOTOES -->
        <div class="row text-right">
          <div class="form-group">
            <div class="col-xs-12">
              <a class="btn btn-white" href="@Url.Action("Empreendimentos", "Cadastros")">Voltar</a>
              <button class="btn btn-primary" type="submit" id="btnCadastrar" data-loading-text="<i class='fa fa-circle-notch fa-spin'></i>">Salvar</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
}

@section scripts {
  @Scripts.Render("~/bundles/admin/js/minha-conta")
}