Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/ViewModels/Cadastros/ControleViewModel.cs
using System;

namespace Open.ProjetoPadrao.Web.ViewModels.Admin
{
  public class ControleViewModel
  {
    public Guid IDControle { get; set; }

    public string Nome { get; set; }
  
    public string Icone { get; set; }

    public string Descricao { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Controllers/CadastrosController.cs
using AutoMapper;
using Newtonsoft.Json;
using Open.Framework.Classes;
using Open.Framework.Uteis;
using Open.Framework.Enums;
using Open.Framework.Extensoes;
using Open.ProjetoPadrao.Web.Entities;
using Open.ProjetoPadrao.Web.Enums;
using Open.ProjetoPadrao.Web.UnitOfWork;
using Open.ProjetoPadrao.Web.ViewModels.Admin;
using Open.ProjetoPadrao.Web.Properties;
using System;
using System.Linq;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using System.Text.RegularExpressions;

namespace Open.ProjetoPadrao.Web.Areas.Admin.Controllers
{
  public class CadastrosController : BaseController
  {
    private Arquivos frameworkArquivo;

    public CadastrosController(IUnitOfWork unitOfWork) : base(unitOfWork)
    {
      frameworkArquivo = new Arquivos();
    }

    #region Páginas

    [HttpGet]
    public ActionResult Paginas()
    {
      return View(BuscarPaginas());
    }

    [HttpGet]
    public ActionResult NovaPagina()
    {
      if (!UsuarioLogado.ActionsPermitidas.Contains("paginas"))
        return RedirectToAction("Index", "Principal");

      if (!UsuarioLogado.SuperUser && !UsuarioLogado.CadastraPagina)
        return RedirectToAction("Paginas");

      return RedirectToAction("Pagina", new { id = Guid.NewGuid() });
    }

    [HttpGet]
    public ActionResult Pagina(Guid id)
    {
      if (!UsuarioLogado.ActionsPermitidas.Contains("paginas"))
        return RedirectToAction("Index", "Principal");

      var model = _unitOfWork.PaginaRepository.BuscarPagina(id);

      if (model == null)
      {
        model = new Pagina();

        model.IDPagina = id;
        model.Nome = "Página sem nome";
        model.PaginaControles = new List<PaginaControle>();

        _unitOfWork.PaginaRepository.CadastrarPagina(model);
      }

      var viewModel = Mapper.Map<Pagina, PaginaViewModel>(model);

      viewModel.ListaControles = _unitOfWork.ControleRepository
       .BuscarControles();

      return View(viewModel);
    }

    [HttpPost]
    public ActionResult RemoverPagina(Guid idPagina)
    {
      if (!UsuarioLogado.ActionsPermitidas.Contains("paginas"))
        return Json(new RetornoJson(true, "Seu usuário não tem permissão para esta ação", string.Empty));

      if (!UsuarioLogado.SuperUser && !UsuarioLogado.EditaPagina)
        return RedirectToAction("Paginas");

      _unitOfWork.PaginaControleImagemRepository.RemoverControleImagens(idPagina);
      _unitOfWork.PaginaControleRepository.RemoverTodosControlesPagina(idPagina);
      _unitOfWork.PaginaRepository.RemoverPagina(idPagina);

      return PartialView("_PartialGridPaginas", BuscarPaginas());
    }

    [HttpPost]
    public void SalvarPagina(Guid idPagina, string nomePagina)
    {
      if ((UsuarioLogado.SuperUser || UsuarioLogado.EditaPagina) && UsuarioLogado.ActionsPermitidas.Contains("paginas"))
        _unitOfWork.PaginaRepository.SalvarPagina(idPagina, nomePagina);
    }

    private IEnumerable<PaginasViewModel> BuscarPaginas()
    {
      return Mapper
        .Map<IEnumerable<Pagina>, IEnumerable<PaginasViewModel>>(_unitOfWork.PaginaRepository.BuscarPaginas());
    }

    #endregion

    #region Controles

    [HttpPost]
    public ActionResult AdicionarControlePagina(Guid idControle, Guid idPagina)
    {
      if (!UsuarioLogado.ActionsPermitidas.Contains("paginas"))
        return RedirectToAction("Index", "Principal");

      var controlePagina = new PaginaControle()
      {
        IDPaginaControle = Guid.NewGuid(),
        IDPagina = idPagina,
        IDControle = idControle,
        Configurado = false
      };

      _unitOfWork.PaginaControleRepository
        .AdicionarControlePagina(controlePagina);

      var model = _unitOfWork.PaginaControleRepository
        .BuscarControlesPagina(idPagina);

      return PartialView("_PartialGridPaginaControles", model);
    }

    [HttpGet]
    public ActionResult ConfiguracaoControle(Guid id)
    {
      if (!UsuarioLogado.SuperUser && !UsuarioLogado.EditaPagina)
        return RedirectToAction("Paginas");

      var model = _unitOfWork.PaginaControleRepository
        .BuscarControlePagina(id);

      if (model.PaginaControleImagens == null)
        model.PaginaControleImagens = new List<PaginaControleImagem>();

      return View(model);
    }

    [HttpPost]
    public ActionResult DeletarControlePagina(Guid idPaginaControle)
    {
      if (!UsuarioLogado.SuperUser && !UsuarioLogado.CadastraPagina)
        return RedirectToAction("Paginas");

      Guid idPagina = _unitOfWork.PaginaControleRepository
        .RemoverControlePagina(idPaginaControle);

      var model = _unitOfWork.PaginaControleRepository
        .BuscarControlesPagina(idPagina);

      return PartialView("_PartialGridPaginaControles", model);
    }

    [HttpPost]
    public void ConfigurarHeadline(Guid idPaginaControle, string identificador, string textoHeadline, string textoHeadlineEN)
    {
      if (UsuarioLogado.SuperUser || UsuarioLogado.EditaPagina)
      {
        var listaParametros = new List<PaginaControleParametro>();
        listaParametros.Add(new PaginaControleParametro()
        {
          IDPaginaControleParametro = Guid.NewGuid(),
          IDPaginaControle = idPaginaControle,
          ConteudoHeadline = textoHeadline,
          ConteudoHeadlineEN = textoHeadlineEN
        });

        _unitOfWork.PaginaControleParametroRepository.RemoverTodosParametrosControle(idPaginaControle);

        if (!string.IsNullOrEmpty(identificador))
          _unitOfWork.PaginaControleRepository.AtualizarConfiguracaoControlePagina(idPaginaControle, identificador);

        SalvarPaginaControleParametros(listaParametros);
      }
    }

    [HttpPost, ValidateInput(false)]
    public void ConfigurarTexto(Guid idPaginaControle, string identificador, string conteudoTexto, string conteudoTextoEN)
    {
      if (UsuarioLogado.SuperUser || UsuarioLogado.EditaPagina)
      {
        var listaParametros = new List<PaginaControleParametro>();
        listaParametros.Add(new PaginaControleParametro()
        {
          IDPaginaControleParametro = Guid.NewGuid(),
          IDPaginaControle = idPaginaControle,
          ConteudoTexto = conteudoTexto,
          ConteudoTextoEN = conteudoTextoEN
        });

        _unitOfWork.PaginaControleParametroRepository.RemoverTodosParametrosControle(idPaginaControle);

        if (!string.IsNullOrEmpty(identificador))
          _unitOfWork.PaginaControleRepository.AtualizarConfiguracaoControlePagina(idPaginaControle, identificador);

        SalvarPaginaControleParametros(listaParametros);
      }
    }

    [HttpPost, ValidateInput(false)]
    public void ConfigurarTitleDescription(Guid idPaginaControle, string identificador, string conteudoTitle, string conteudoDescription, string conteudoTitleEN, string conteudoDescriptionEN)
    {
      if (UsuarioLogado.SuperUser || UsuarioLogado.EditaPagina)
      {
        var listaParametros = new List<PaginaControleParametro>();
        listaParametros.Add(new PaginaControleParametro()
        {
          IDPaginaControleParametro = Guid.NewGuid(),
          IDPaginaControle = idPaginaControle,
          ConteudoTitle = conteudoTitle,
          ConteudoDescription = conteudoDescription,
          ConteudoTitleEN = conteudoTitleEN,
          ConteudoDescriptionEN = conteudoDescriptionEN
        });

        _unitOfWork.PaginaControleParametroRepository.RemoverTodosParametrosControle(idPaginaControle);

        if (!string.IsNullOrEmpty(identificador))
          _unitOfWork.PaginaControleRepository.AtualizarConfiguracaoControlePagina(idPaginaControle, identificador);

        SalvarPaginaControleParametros(listaParametros);
      }
    }

    [HttpPost]
    public void EnviarImagemGaleria(Guid idPaginaControle)
    {
      var anexo = frameworkArquivo
        .PrepararArquivo("Imagens/Galeria", idPaginaControle, Request.Files[0], TipoArquivo.Imagem, TipoHospedagemArquivo.LOCAL);

      if (anexo != null)
      {
        var model = new PaginaControleImagem
        {
          Arquivo = anexo,
          IDArquivo = anexo.IDArquivo,
          IDPaginaControleImagem = Guid.NewGuid(),
          IDPaginaControle = idPaginaControle
        };

        _unitOfWork.PaginaControleImagemRepository.SalvarControleImagem(model);
      }
    }

    [HttpPost]
    public ActionResult RemoverImagemGaleria(Guid idPaginaControle, Guid idPaginaControleImagem)
    {
      var model = _unitOfWork.PaginaControleImagemRepository
        .BuscarPaginaControleImagem(idPaginaControleImagem);

      if (model != null)
      {
        string caminhoPastaGaleria = string.Format("{0}Uploads/Imagens/Galeria/{1}",
         AppDomain.CurrentDomain.BaseDirectory,
         idPaginaControle);

        string caminhoArquivo = string.Format("{0}/{1}{2}", caminhoPastaGaleria,
          model.Arquivo.NomeHash, model.Arquivo.Extensao);

        if (System.IO.File.Exists(caminhoArquivo))
          System.IO.File.Delete(caminhoArquivo);

        _unitOfWork.PaginaControleImagemRepository.RemoverPaginaControleImagem(model);
      }

      return BuscarImagensGaleria(idPaginaControle);
    }

    [HttpPost]
    public JsonResult SalvarImagemGaleria(Guid idPaginaControleImagem, string alt, string title, string legenda, string titulo, string subTitulo, string urlRedirecionamento, string altEN, string titleEN, string legendaEN, string tituloEN, string subTituloEN, string urlRedirecionamentoEN)
    {
      var retorno = new RetornoJson(false, "Imagem salva com sucesso", string.Empty);

      try
      {
        _unitOfWork.PaginaControleImagemRepository
          .SalvarDetalhesPaginaControleImagem(idPaginaControleImagem, alt, title, legenda, titulo, subTitulo, urlRedirecionamento, altEN, titleEN, legendaEN, tituloEN, subTituloEN, urlRedirecionamentoEN);
      }
      catch
      {
        retorno.Erro = true;
        retorno.Mensagem = "Ocorreu um erro ao salvar a imagem";
      }

      return Json(retorno);
    }

    [HttpPost]

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Controllers/BaseController.cs
using AutoMapper;
using Open.ProjetoPadrao.Web.Entities;
using Open.ProjetoPadrao.Web.ViewModels.Site;
using Open.ProjetoPadrao.Web.Enums;
using Open.ProjetoPadrao.Web.Properties;
using Open.ProjetoPadrao.Web.UnitOfWork;
using Open.ProjetoPadrao.Web.Attributes;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Collections.Generic;

namespace Open.ProjetoPadrao.Web.Controllers
{
  [Localization("pt-BR")]
  public abstract class BaseController : Areas.Admin.Controllers.BaseController
  {
    public BaseController(IUnitOfWork unitOfWork) : base(unitOfWork) { }

    internal Pagina CarregarPagina(string identificadorPagina)
    {
      return _unitOfWork.PaginaRepository.BuscarPagina(identificadorPagina);
    }
    internal VitrineViewModel CarregarVitrine(Pagina pagina, string nomeIdentificadorControle)
    {
      if (pagina != null)
      {
        if (pagina.PaginaControles != null && pagina.PaginaControles.Count > 0)
        {
          PaginaControle galeriaControle = pagina.PaginaControles.FirstOrDefault(s => !string.IsNullOrEmpty(s.NomeIdentificadorControle) &&
          s.NomeIdentificadorControle.Equals(nomeIdentificadorControle));

          if (galeriaControle != null)
          {
            PaginaControleImagem galeriaParametro = galeriaControle.PaginaControleImagens.FirstOrDefault();
            return Mapper.Map<PaginaControleImagem, VitrineViewModel>(galeriaParametro);
          }
        }
      }

      return new VitrineViewModel();
    }
    internal string CarregarTexto(Pagina pagina, string nomeIdentificadorControle, Idioma idioma)
    {
      string paginaParametro = string.Empty;

      if (pagina != null)
      {
        PaginaControle paginaControle = pagina.PaginaControles.FirstOrDefault(s => !string.IsNullOrEmpty(s.NomeIdentificadorControle) &&
        s.NomeIdentificadorControle.Equals(nomeIdentificadorControle));

        if (paginaControle != null)
        {
          if (idioma == Idioma.pt)
          {
            paginaParametro = paginaControle.PaginaControleParametros.FirstOrDefault().ConteudoTexto;
          }
          else
          {
            paginaParametro = paginaControle.PaginaControleParametros.FirstOrDefault().ConteudoTextoEN;
          }
        }
      }

      return paginaParametro;
    }
    internal string CarregarTitle(Pagina pagina, string nomeIdentificadorControle, Idioma idioma)
    {
      string paginaParametro = string.Empty;

      if (pagina != null)
      {
        PaginaControle paginaControle = pagina.PaginaControles.FirstOrDefault(s => !string.IsNullOrEmpty(s.NomeIdentificadorControle) &&
        s.NomeIdentificadorControle.Equals(nomeIdentificadorControle));

        if (paginaControle != null)
        {
          if (idioma == Idioma.pt)
          {
            paginaParametro = paginaControle.PaginaControleParametros.FirstOrDefault() == null ? string.Empty :
              paginaControle.PaginaControleParametros.FirstOrDefault().ConteudoTitle;
          }
          else
          {
            paginaParametro = paginaControle.PaginaControleParametros.FirstOrDefault() == null ? string.Empty :
              paginaControle.PaginaControleParametros.FirstOrDefault().ConteudoTitleEN;
          }
        }
      }

      return paginaParametro;
    }
    internal string CarregarDescription(Pagina pagina, string nomeIdentificadorControle, Idioma idioma)
    {
      string paginaParametro = string.Empty;

      if (pagina != null)
      {
        PaginaControle paginaControle = pagina.PaginaControles.FirstOrDefault(s => !string.IsNullOrEmpty(s.NomeIdentificadorControle) &&
        s.NomeIdentificadorControle.Equals(nomeIdentificadorControle));

        if (paginaControle != null)
        {
          if (idioma == Idioma.pt)
          {
            paginaParametro = paginaControle.PaginaControleParametros.FirstOrDefault() == null ? string.Empty :
              paginaControle.PaginaControleParametros.FirstOrDefault().ConteudoDescription;
          }
          else
          {
            paginaParametro = paginaControle.PaginaControleParametros.FirstOrDefault() == null ? string.Empty :
              paginaControle.PaginaControleParametros.FirstOrDefault().ConteudoDescriptionEN;
          }
        }
      }

      return paginaParametro;
    }
    internal string CarregarHead(Pagina pagina, string nomeIdentificadorControle, Idioma idioma)
    {
      string paginaParametro = string.Empty;

      if (pagina != null)
      {
        PaginaControle paginaControle = pagina.PaginaControles.FirstOrDefault(s => !string.IsNullOrEmpty(s.NomeIdentificadorControle) &&
        s.NomeIdentificadorControle.Equals(nomeIdentificadorControle));

        if (paginaControle != null)
        {
          if (idioma.Equals(Idioma.pt))
          {
            paginaParametro = paginaControle.PaginaControleParametros.FirstOrDefault().ConteudoHeadline;
          }
          else
          {
            paginaParametro = paginaControle.PaginaControleParametros.FirstOrDefault().ConteudoHeadlineEN;
          }
        }
      }

      return paginaParametro;
    }
    internal IEnumerable<VitrineViewModel> CarregarGaleria(Pagina pagina, string nomeIdentificadorControle)
    {
      if (pagina != null)
      {
        PaginaControle galeriaControle = pagina.PaginaControles.FirstOrDefault(s => s.NomeIdentificadorControle.Equals(nomeIdentificadorControle));
        if (galeriaControle != null)
        {
          IEnumerable<PaginaControleImagem> galeriaParametro = galeriaControle.PaginaControleImagens;
          return galeriaParametro != null ? Mapper.Map<IEnumerable<VitrineViewModel>>(galeriaParametro) : Enumerable.Empty<VitrineViewModel>();
        }
      }

      return Enumerable.Empty<VitrineViewModel>();
    }
    internal void EnviarEmail(string nomeEmail, string conteudo, string responderPara)
    {
      #if DEBUG
        ConfiguracaoEmail.EnviarEmail(nomeEmail, conteudo, responderPara, new string[] { Configs.MailTo });
      #else
        ConfiguracaoEmail.EnviarEmail(nomeEmail, conteudo, responderPara, new string[] { Configs.MailTo });
      #endif
    }
    internal string BuscarModelo(TipoEmail tipo)
    {
      string retorno = string.Empty;

      switch (tipo)
      {
        case TipoEmail.Contato:
          retorno = System.IO.File.ReadAllText(Server.MapPath("~/Email/modelo-contato.html"));
          break;
        case TipoEmail.Empreendimento:
          retorno = System.IO.File.ReadAllText(Server.MapPath("~/Email/modelo-empreendimento.html"));
          break;
        case TipoEmail.FaleConosco:
          retorno = System.IO.File.ReadAllText(Server.MapPath("~/Email/modelo-faleconosco.html"));
          break;
        case TipoEmail.Parceria:
          retorno = System.IO.File.ReadAllText(Server.MapPath("~/Email/modelo-parceria.html"));
          break;
        case TipoEmail.LigamosParaVoce:
          retorno = System.IO.File.ReadAllText(Server.MapPath("~/Email/modelo-ligamos.html"));
          break;
        case TipoEmail.VendaSeuTerreno:
          retorno = System.IO.File.ReadAllText(Server.MapPath("~/Email/modelo-vendaseuterreno.html"));
          break;
      }

      return retorno;
    }
    internal Idioma BuscarIdiomaAtual()
    {
      CultureInfo currentCulture = Thread.CurrentThread.CurrentCulture;

      if (currentCulture.Name.Equals(Configs.Portugues))
        return Idioma.pt;
      else return Idioma.en;
    }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Cadastros/Bairros.cshtml
@model IEnumerable<Open.ProjetoPadrao.Web.ViewModels.Admin.BairrosViewModel>
@{
  ViewBag.Title = "Bairros";
  Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">
    <h2>Bairros</h2>
    <ol class="breadcrumb">
      <li>
        <a href="@Url.Action("Index", "Principal")">Dashboard</a>
      </li>
      <li>
        <a href="#">Cadastros</a>
      </li>
      <li class="active">
        <strong>Bairros</strong>
      </li>
    </ol>
  </div>
</div>
<div class="wrapper wrapper-content">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <div class="ibox-tools">
        <a href="@Url.Action("NovoBairro", "Cadastros")" class="btn btn-w-m btn-primary">Adicionar</a>
      </div>
    </div>
    <div class="ibox-content padding-bottom" id="divBairros">
      @{ Html.RenderPartial("_PartialGridBairros", Model); }
    </div>
  </div>
</div>

<input type="hidden" id="urlRemoverBairro" value="@Url.Action("RemoverBairro", "Cadastros")" />

@section scripts {
  @Scripts.Render("~/bundles/admin/js/bairro")
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Cadastros/NovoVideo.cshtml
@model Open.ProjetoPadrao.Web.ViewModels.Admin.VideoViewModel
@{
  ViewBag.Title = "Novo Vídeo";
  Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">
    <h2>Novo Vídeo</h2>
    <ol class="breadcrumb">
      <li>
        <a href="@Url.Action("Index", "Principal")">Dashboard</a>
      </li>
      <li>
        <a href="#">Cadastros</a>
      </li>
      <li>
        <a href="@Url.Action("Videos", "Cadastros")">Vídeos</a>
      </li>
      <li class="active">
        <strong>Novo Vídeo</strong>
      </li>
    </ol>
  </div>
</div>

@using (Ajax.BeginForm("CadastrarVideo", "Cadastros",
       new AjaxOptions()
       {
         HttpMethod = "POST",
         OnBegin = "inicioCadastro",
         OnSuccess = "sucessoCadastro",
         OnFailure = "falhaCadastro",
       },
       new { id = "formCadastroVideo", @class = "m-t", role = "form" }))
{
  @Html.AntiForgeryToken()

  <div class="wrapper wrapper-content">
    @{ Html.RenderPartial("_PartialVideo", Model); }
  </div>
}

@section scripts {
  @Scripts.Render("~/bundles/admin/js/video")
} 

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Cadastros/Paginas.cshtml
@model IEnumerable<Open.ProjetoPadrao.Web.ViewModels.Admin.PaginasViewModel>
@{
  ViewBag.Title = "Páginas";
  Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">
    <h2>Páginas</h2>
    <ol class="breadcrumb">
      <li>
        <a href="@Url.Action("Index", "Principal")">Dashboard</a>
      </li>
      <li>
        <a href="#">Cadastros</a>
      </li>
      <li class="active">
        <strong>Páginas</strong>
      </li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content">
      <div class="ibox float-e-margins">
        @if (UsuarioLogado.SuperUser || UsuarioLogado.CadastraPagina)
        {
          <div class="ibox-title">
            <div class="ibox-tools">
              <a href="@Url.Action("NovaPagina", "Cadastros")" class="btn btn-w-m btn-primary">Adicionar</a>
            </div>
          </div>
        }
        <div class="ibox-content padding-bottom" id="divPaginas">
          @{ Html.RenderPartial("_PartialGridPaginas", Model); }
        </div>
      </div>
    </div>
  </div>
</div>

@section scripts {
  @Scripts.Render("~/bundles/admin/js/pagina")
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Cadastros/Video.cshtml
@model Open.ProjetoPadrao.Web.ViewModels.Admin.VideoViewModel
@{
  ViewBag.Title = Model.Titulo;
  Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">
    <h2>@Model.Titulo</h2>
    <ol class="breadcrumb">
      <li>
        <a href="@Url.Action("Index", "Principal")">Dashboard</a>
      </li>
      <li>
        <a href="#">Cadastros</a>
      </li>
      <li>
        <a href="@Url.Action("Videos", "Cadastros")">Vídeos</a>
      </li>
      <li class="active">
        <strong>@Model.Titulo</strong>
      </li>
    </ol>
  </div>
</div>
@using (Ajax.BeginForm("EditarVideo", "Cadastros",
       new AjaxOptions()
       {
         HttpMethod = "POST",
         OnBegin = "inicioCadastro",
         OnSuccess = "sucessoCadastro",
         OnFailure = "falhaCadastro",
       },
       new { id = "formVideo", @class = "m-t", role = "form" }))
{
  @Html.AntiForgeryToken()
  <div class="wrapper wrapper-content">
    @{ Html.RenderPartial("_PartialVideo", Model); }
  </div>
  @Html.HiddenFor(a => a.IDVideo)
  @Html.HiddenFor(a => a.DataCriacao)
}

@section scripts {
  @Scripts.Render("~/bundles/admin/js/video")
} 

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Cadastros/Videos.cshtml
@model IEnumerable<Open.ProjetoPadrao.Web.ViewModels.Admin.VideosViewModel>
@{
  ViewBag.Title = "Vídeos";
  Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">
    <h2>Vídeos</h2>
    <ol class="breadcrumb">
      <li>
        <a href="@Url.Action("Index", "Principal")">Dashboard</a>
      </li>
      <li>
        <a href="#">Cadastros</a>
      </li>
      <li class="active">
        <strong>Vídeos</strong>
      </li>
    </ol>
  </div>
</div>
<div class="wrapper wrapper-content">
  <div class="ibox float-e-margins">
    <div class="ibox-title">
      <div class="ibox-tools">
        <a href="@Url.Action("NovoVideo", "Cadastros")" class="btn btn-w-m btn-primary">Adicionar</a>
      </div>
    </div>
    <div class="ibox-content padding-bottom" id="divVideos">
      @{ Html.RenderPartial("_PartialGridVideos", Model); }
    </div>
  </div>
</div>

<input type="hidden" id="urlRemoverVideo" value="@Url.Action("RemoverVideo", "Cadastros")" />

@section scripts {
  @Scripts.Render("~/bundles/admin/js/video")
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Cadastros/_PartialBairro.cshtml
@model Open.ProjetoPadrao.Web.ViewModels.Admin.BairroViewModel

<div class="ibox float-e-margins">
  <div class="ibox-title">
    <h5>Dados Gerais</h5>
  </div>
  <div class="ibox-content padding-bottom">
    <div class="row">
      <div class="form-group">
        <div class="col-lg-3">
          @Html.LabelFor(a => a.IDEstado)
          @Html.DropDownListFor(a => a.IDEstado, Model.ListaEstados, "-- Estado --", new { @class = "form-control m-b", data_url = Url.Action("BuscarCidades", "Base") })
          @Html.ValidationMessageFor(a => a.IDEstado)
        </div>
        <div class="col-lg-3">
          @Html.LabelFor(a => a.IDCidade)
          @Html.DropDownListFor(a => a.IDCidade, Model.ListaCidades == null ? Enumerable.Empty<SelectListItem>() : Model.ListaCidades, Model.ListaCidades == null ? "-- Selecione o Estado --" : "-- Cidade --", new { @class = "form-control m-b" })
          @Html.ValidationMessageFor(a => a.IDCidade)
        </div>
        <div class="col-lg-4">
          @Html.LabelFor(a => a.Nome)
          @Html.TextBoxFor(a => a.Nome, new { placeholder = "Nome do Bairro", @class = "form-control m-b" })
          @Html.ValidationMessageFor(a => a.Nome)
        </div>
      </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="row text-right">
      <div class="form-group">
        <div class="col-xs-12">
          <a href="@Url.Action("Bairros", "Cadastros")" class="btn btn-white">Voltar</a>
          <button class="btn btn-primary" type="submit" id="btnCadastrar" data-loading-text="<i class='fa fa-circle-notch fa-spin'></i>">Salvar</button>
        </div>
      </div>
    </div>
  </div>
</div>