Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/ViewModels/Consultas/ContatoGeralViewModel.cs
using System;

namespace Open.ProjetoPadrao.Web.ViewModels.Admin
{
  public sealed class ContatoGeralViewModel
  {
    public ContatoGeralViewModel()
    {
      IDContato = Guid.NewGuid();
    }

    public Guid IDContato { get; set; }
    public string Nome { get; set; }
    public string Email { get; set; }
    public string Telefone { get; set; }
    public string Celular { get; set; }
    public string Assunto { get; set; }
    public string Mensagem { get; set; }
    public int Departamento { get; set; }
    public DateTime DataHoraInclusao { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/ViewModels/Consultas/ContatoViewModel.cs
using Open.ProjetoPadrao.Web.Enums;

namespace Open.ProjetoPadrao.Web.ViewModels.Admin
{
  public class ContatoViewModel
  {
    public object ObjContato { get; set; }
    public string Origem { get; set; }
    public TipoContato TipoContato { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/ViewModels/Consultas/ContatosViewModel.cs
using System;

namespace Open.ProjetoPadrao.Web.ViewModels.Admin
{
  public class ContatosViewModel
  {
    public Guid IDContato { get; set; }
    public string Email { get; set; }
    public string Telefone { get; set; }
    public string Celular { get; set; }

    public DateTime DataHoraInclusao { get; set; }
    public bool Visualizado { get; set; }
    public string Origem { get; set; }
    public int QtdAnexos { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/ViewModels/Consultas/NewsletterViewModel.cs
using System;

namespace Open.ProjetoPadrao.Web.ViewModels.Admin
{
  public sealed class NewsletterViewModel
  {
    public Guid IDNewsletter { get; set; }
    public string Nome { get; set; }
    public string Email { get; set; }
    public string Telefone { get; set; }
    public bool ReceberWhatsapp { get; set; }
    public bool ReceberTelefone { get; set; }
    public DateTime DataCadastro { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Entities/Contato.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Open.ProjetoPadrao.Web.Enums;

namespace Open.ProjetoPadrao.Web.Entities
{
  [Table("Contato")]
  public class Contato
  {
    public Contato()
    {
      ListaContatoAnexo = new Collection<ContatoAnexo>();
    }

    [Key]
    public Guid IDContato { get; set; }

    [MaxLength(255)]
    public string Nome { get; set; }

    [Required, MaxLength(255)]
    public string Email { get; set; }

    [MaxLength(20)]
    public string Telefone { get; set; }

    [MaxLength(255)]
    public string Assunto { get; set; }

    [MaxLength(500)]
    public string Mensagem { get; set; }

    [MaxLength(255)]
    public string Departamento { get; set; }

    [Required]
    public int CodigoTipoContato
    {
      get
      {
        return (int)TipoContato;
      }
      set
      {
        TipoContato = (TipoContato)value;
      }
    }

    [EnumDataType(typeof(TipoContato)), NotMapped]
    public TipoContato TipoContato { get; set; }

    public bool Visualizado { get; set; }

    [Required]
    public DateTime DataHoraInclusao { get; set; }

    [MaxLength(20)]
    public string Celular { get; set; }

    [MaxLength(255)]
    public string NomeEmpresa { get; set; }

    [MaxLength(255)]
    public string RelacaoTerreno { get; set; }

    [MaxLength(255)]
    public string Parceria { get; set; }

    [MaxLength(500)]
    public string Proposta { get; set; }

    [MaxLength(255)]
    public string NomeEmpreendimento { get; set; }

    public Guid? IDCidade { get; set; }

    public Guid? IDTerreno { get; set; }

    public bool? MoraExterior { get; set; }

    public virtual ICollection<ContatoAnexo> ListaContatoAnexo { get; set; }

    public virtual Cidade Cidade { get; set; }

    [MaxLength(255)]
    public virtual string NumeroContribuinte { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Entities/Newsletter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Open.ProjetoPadrao.Web.Entities
{
  [Table("Newsletter")]
  public class Newsletter
  {
    [Key]
    public Guid IDNewsletter { get; set; }

    [Required, MaxLength(150)]
    public string Nome { get; set; }

    [Required, MaxLength(150)]
    public string Email { get; set; }

    [MaxLength(20)]
    public string Telefone { get; set; }

    [Required]
    public bool ReceberWhatsApp { get; set; }

    [Required]
    public bool ReceberTelefone { get; set; }
  
    [Required]
    public DateTime DataCadastro { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/ViewModels/Componentes/ContatoViewModel.cs
using Open.ProjetoPadrao.Web.Enums;
using System;
using System.Web.Mvc;

namespace Open.ProjetoPadrao.Web.ViewModels.Site
{
  public class ContatoViewModel
  {
    public ContatoViewModel()
    {
      IDContato = Guid.NewGuid();
    }

    public Guid IDContato { get; set; }
    public string Nome { get; set; }
    public string Email { get; set; }
    public string Telefone { get; set; }
    public string Celular { get; set; }
    public string Mensagem { get; set; }
    public string NomeEmpresa { get; set; }
    public string NomeEmpreendimento { get; set; }
    public int RelacaoTerreno { get; set; }
    public string Proposta { get; set; }
    public bool CadastrarNewsletter { get; set; }
    public Guid IDEstado { get; set; }
    public Guid IDCidade { get; set; }
    public Guid IDEmpreendimento { get; set; }
    public bool MoraExterior { get; set; }
    public TipoContato TipoContato { get; set; }
    public string Controller { get; set; }
    public string NumeroContribuinte { get; set; }

    public SelectList Estados { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/ViewModels/Layout/NewsLetterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Open.ProjetoPadrao.Web.ViewModels.Site
{
  public sealed class NewsLetterViewModel
  {
    public string Nome { get; set; }
    public string Email { get; set; }
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Controllers/ConsultasController.cs
using AutoMapper;
using Open.ProjetoPadrao.Web.Entities;
using Open.ProjetoPadrao.Web.UnitOfWork;
using Open.ProjetoPadrao.Web.ViewModels.Admin;
using Open.ProjetoPadrao.Web.Enums;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Open.ProjetoPadrao.Web.Areas.Admin.Controllers
{
  public class ConsultasController : BaseController
  {
    public ConsultasController(IUnitOfWork unitOfWork) : base(unitOfWork) { }

    #region Contatos

    [HttpGet]
    public ActionResult Contatos()
    {
      return View(BuscarContatos());
    }

    [HttpPost]
    public ActionResult RemoverContato(Guid idContato)
    {
      _unitOfWork.ContatoRepository.RemoverContato(idContato);
      return PartialView("_PartialGridContatos", BuscarContatos());
    }

    [HttpGet]
    public ActionResult Contato(Guid id)
    {
      _unitOfWork.ContatoRepository.AtualizarContatoVisualizado(id);
      var model = _unitOfWork.ContatoRepository.CarregarContato(id);

      var viewModel = Mapper.Map<Contato, ContatoViewModel>(model);

      switch (model.TipoContato)
      {
        case TipoContato.Contato:
          viewModel.ObjContato = BindMapperViewModel<ContatoGeralViewModel>(model);
          break;
      }

      return View(viewModel);
    }

    private T BindMapperViewModel<T>(Contato contato) where T : class
    {
      return Mapper.Map<Contato, T>(contato);
    }

    private IEnumerable<ContatosViewModel> BuscarContatos()
    {
      return Mapper
       .Map<IEnumerable<Contato>, IEnumerable<ContatosViewModel>>
       (_unitOfWork.ContatoRepository.BuscarContatos());
    }

    #endregion

    #region Newsletter

    [HttpGet]
    public ActionResult Newsletters()
    {
      return View(BuscarNewsletter());
    }

    [HttpPost]
    public ActionResult RemoverNewsletter(Guid idNewsletter)
    {
      _unitOfWork.NewsletterRepository.RemoverNewsletter(idNewsletter);
      return PartialView("_PartialGridNewsletters", BuscarNewsletter());
    }

    private IEnumerable<NewsletterViewModel> BuscarNewsletter()
    {
      return Mapper
       .Map<IEnumerable<Newsletter>, IEnumerable<NewsletterViewModel>>(_unitOfWork.NewsletterRepository.ListarNewsletters());
    }

    #endregion
  }
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Consultas/Contato.cshtml
@using Open.ProjetoPadrao.Web.Enums
@using Open.ProjetoPadrao.Web.ViewModels.Admin

@model Open.ProjetoPadrao.Web.ViewModels.Admin.ContatoViewModel

@{
  ViewBag.Title = "Contato - " + Model.Origem;
  Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">

    <div id="divNomePagina" class="cursor-pointer">
      <h2>Contato - @Model.Origem</h2>
    </div>

    <ol class="breadcrumb">
      <li><a href="@Url.Action("Index", "Principal")">Dashboard</a></li>
      <li><a href="#">Cadastros</a></li>
      <li><a href="@Url.Action("Paginas", "Cadastros")">Páginas</a></li>
      <li class="active"><strong id="lblNomePagina">Contato - @Model.Origem</strong></li>
    </ol>
  </div>
</div>

@switch (Model.TipoContato)
{
  case TipoContato.Empreendimento:
    Html.RenderPartial("_PartialContatoEmpreendimento", (ContatoGeralViewModel)Model.ObjContato);
    break;
  case TipoContato.FaleConosco:
    Html.RenderPartial("_PartialContatoFaleConosco", (FaleConoscoViewModel)Model.ObjContato);
    break;
  case TipoContato.VendaSeuTerreno:
    Html.RenderPartial("_PartialContatoVendaSeuTerreno", (VendaSeuTerrenoViewModel)Model.ObjContato);
    break;
  case TipoContato.Parceria:
    Html.RenderPartial("_PartialContatoParceiro", (SejaParceiroViewModel)Model.ObjContato);
    break;
  case TipoContato.Contato:
    Html.RenderPartial("_PartialContato", (ContatoGeralViewModel)Model.ObjContato);
    break;
  case TipoContato.LigamosParaVoce:
    Html.RenderPartial("_PartialContatoLigamosParaVoce", (LigamosParaVoceViewModel)Model.ObjContato);
    break;
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Consultas/Contatos.cshtml
@model IEnumerable<Open.ProjetoPadrao.Web.ViewModels.Admin.ContatosViewModel>
@{
  ViewBag.Title = "Contatos";
  Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">
    <h2>Contatos</h2>
    <ol class="breadcrumb">
      <li>
        <a href="@Url.Action("Index", "Principal")">Dashboard</a>
      </li>
      <li>
        <a href="#">Consultas</a>
      </li>
      <li class="active">
        <strong>Contatos</strong>
      </li>
    </ol>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content">
      <div class="ibox float-e-margins">
        <div class="ibox-content padding-bottom" id="divGridContatos">
          @{ Html.RenderPartial("_PartialGridContatos", Model); }
        </div>
      </div>
    </div>
  </div>
</div>

@section scripts {
  @Scripts.Render("~/bundles/admin/js/contato")
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Consultas/Newsletters.cshtml
@model List<Open.ProjetoPadrao.Web.ViewModels.Admin.NewsletterViewModel>
@{
  ViewBag.Title = "Newsletters";
  Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-12">
    <h2>Newsletters</h2>

    <ol class="breadcrumb">
      <li><a href="@Url.Action("Index", "Principal")">Dashboard</a></li>
      <li><a href="#">Consultas</a></li>
      <li class="active"><strong>Newsletter</strong></li>
    </ol>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="wrapper wrapper-content">
      <div class="ibox float-e-margins">
        <div class="ibox-content padding-bottom" id="divNewsletters">
          @{ Html.RenderPartial("_PartialGridNewsletters", Model); }
        </div>
      </div>
    </div>
  </div>
</div>

@section scripts {
  @Scripts.Render("~/bundles/admin/js/newsletter")
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Consultas/_PartialContato.cshtml
@model Open.ProjetoPadrao.Web.ViewModels.Admin.ContatoGeralViewModel

<div class="wrapper wrapper-content">
  <div class="ibox float-e-margins">
    <div class="ibox-content padding-bottom">

      <!-- DATA -->
      <div class="row">
        <div class="form-group">
          <div class="col-xs-4">
            <h3><strong>Data cadastro:</strong> @Model.DataHoraInclusao.ToString("dd/MM/yyyy - HH:mm")</h3>
          </div>
        </div>
      </div>

      <!-- NOME -->
      <div class="row">
        <div class="form-group">
          <div class="col-xs-4">
            <h3><strong>Nome:</strong> @Model.Nome</h3>
          </div>
        </div>
      </div>

      <!-- EMAIL -->
      <div class="row">
        <div class="form-group">
          <div class="col-xs-4">
            <h3><strong>E-mail:</strong> @Model.Email</h3>
          </div>
        </div>
      </div>

      <!-- TELEFONE -->
      <div class="row">
        <div class="form-group">
          <div class="col-xs-4">
            <h3><strong>Telefone:</strong> @Model.Telefone</h3>
          </div>
        </div>
      </div>
      <div class="hr-line-dashed"></div>

      <!-- BOTOES -->
      <div class="row text-right">
        <div class="form-group">
          <div class="col-xs-12">
            @Html.ActionLink("Voltar", "Contatos", "Consultas", null, new { @class = "btn btn-white" })
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Consultas/_PartialGridContatos.cshtml
@model IEnumerable<Open.ProjetoPadrao.Web.ViewModels.Admin.ContatosViewModel>

@if (Model != null && Model.Count() > 0)
{
  <table class="table table-striped" data-tipo="datatable">
    <thead>
      <tr>
        <th>Origem</th>
        <th width="100">Data</th>
        <th>E-mail</th>
        <th>Telefone</th>
        <th>Celular</th>
        <th class="text-center" width="50">Visualizado</th>
        <th width="50">Ações</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
      <tr>
        <td>@item.Origem</td>
        <td>@item.DataHoraInclusao.ToString("dd/MM/yy - HH:mm")</td>
        <td>@(string.IsNullOrEmpty(item.Email) ? "Não informado" : @item.Email)</td>
        <td>@(string.IsNullOrEmpty(item.Telefone) ? "Não informado" : @item.Telefone)</td>
        <td>@(string.IsNullOrEmpty(item.Celular) ? "Não informado" : @item.Celular)</td>
        <td class="text-center">@(item.Visualizado ? "Sim" : "Não")</td>
        <td>
          <a class="btn btn-sm btn-success" href="@Url.Action("Contato", "Consultas", new { id = item.IDContato })">
            <i class="fa fa-eye"></i>
          </a>
          <button data-id="btnRemoverContato" data-idcontato="@item.IDContato" class="btn btn-sm btn-danger" data-url="@Url.Action("RemoverContato", "Consultas")" data-loading-text="<i class='fa fa-circle-notch fa-spin'></i>">
            <i class="fa fa-times"></i>
          </button>
        </td>
      </tr>
      }
    </tbody>
  </table>
}
else
{
  <div class="alert alert-info text-center margin-top-aviso">
    Nenhum contato realizado até o momento
  </div>
}

Open.ProjetoPadrao/Open.ProjetoPadrao.Web/Areas/Admin/Views/Consultas/_PartialGridNewsletters.cshtml
@model List<Open.ProjetoPadrao.Web.ViewModels.Admin.NewsletterViewModel>

@if (Model != null && Model.Count > 0)
{
  <table class="table table-striped" data-tipo="datatable">
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th width="40" class="text-center">Ações</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
        <tr>
          <td>@item.Nome</td>
          <td>@item.Email</td>
          <td class="text-center">
            <button data-id="btnRemoverNewsletter" data-idnewsletter="@item.IDNewsletter" class="btn btn-sm btn-danger" data-urlremover="@Url.Action("RemoverNewsletter", "Consultas")" data-loading-text="<i class='fa fa-circle-notch fa-spin'></i>">
              <i class="fa fa-times"></i>
            </button>
          </td>
        </tr>
      }
    </tbody>
  </table>
}
else
{
  <div class="alert alert-info text-center margin-top-aviso">
    Nenhum cadastro de newsletter feito até o momento
  </div>
}